### ISSUE TITLE
can't make emacs-eclim work

### ISSUE THREAD

**Issue by thorn101** [senny/emacs-eclim#104]
I just installed emacs-eclim from melpa and eclim version 2.2.6 and tried to start it using start-eclimd which doesn't work.

I keep getting "Wrong type argument: stringp, nil".
When I start eclim manually from the eclipse root directory, it starts the eclipse server but when I try to do "eclim-manage-projects" from emacs I get the error "Eclim installation not found. Please set the eclim-executable" even though my installation of the plugin is in the default directory (/Applications/eclipse). Setting the directory manually by doing 

(custom-set-variables
 '(eclim-eclipse-dirs '("/Applications/eclipse")))

does not seem to do anything.

Please help, I would really love to use this.

Alex

**Comment by nickenchev** [comment]
Hey, what is the "/eclim" file supposed to be? I have "eclimd" in my eclipse folder, but no "eclim" file. It works well inside of Vim with the headless/headed setup, I just have no idea what this "eclim-executable" is supposed to point to.
Since I'm on a mac, my Eclipse installation is inside:
/Users/nenchev/eclipse/jee-oxygen/Eclipse.app/Contents/Eclipse

Thanks

**Comment by nickenchev** [comment]
Ended up fixing this by setting those variables to the following:
```
(custom-set-variables
  '(eclim-eclipse-dirs '("/Users/nenchev/eclipse/jee-oxygen/Eclipse.app/Contents/Eclipse"))
  '(eclim-executable "/Users/nenchev/.p2/pool/plugins/org.eclim_2.7.2/bin/eclim"))
```

In what case would the "eclim" executable actually end up in my Eclipse folder?? I'm confused why the docs are asking for a `~/nonStandard/eclipse/eclim"` instead of the p2 folder.

**Comment by Giesch** [comment]
On a mac, I found it in '/Applications/Eclipse.app/Contents/Eclipse/plugins/org.eclim_2.7.2/bin/eclim'.
This could be better documented, but we should probably talk about it on https://github.com/emacs-eclim/emacs-eclim.

**Comment by Naheel-Azawy** [comment]
I spent long time looking for a solution before I reach here. Thank you @nickenchev for sharing your finding. For me, running eclipse from a non standard path under linux, it was in `eclipse_path/plugins/org.eclim_2.7.2/bin/eclim` .
Documentation must be updated as it is very misleading.

**Comment by rileyrg** [comment]
I'm having the same issues. Laughably dire installation instructions. The eclim-installer seems to be designed to ruin my day. But thats Java for you.

**Comment by Beyonder616** [comment]
I'm having the same issues,although even after finding where eclim is,I tried adding this:~/home/beyonder616/.p2/pool/plugins/org.eclim_2.8.0/bin/eclim,it says that no file or directory is there,even if I remove eclim from the file path it says the same.
