### ISSUE TITLE
This project is looking for a new maintainer

### ISSUE THREAD

**Issue by senny** [senny/emacs-eclim#155]
It's been five years since I started this project. Time has passed and my work moved away from the Java world. For the last years, long time committer @fred-o took over the maintenance of this project. He has done an amazing job keeping up with issues and moving this project forward. Thank you!

As @fred-o is moving away from Java as well and has less time to spare on emacs-eclim, we are looking for a new maintainer for this project. If you are interested please contact me.

Cheers,
-- Yves

**Comment by lins05** [comment]
Hi @senny , I'd like to contribute.

I've been using emacs for 6+ years, and emacs-eclim for 3+ years. It really make my life coding java much easier, so I hope I can make some contribution back.

How can I get started?

**Comment by senny** [comment]
@lins05 great to hear! There are several [open issues on GitHub](https://groups.google.com/forum/#!forum/emacs-eclim) and [questions on the GoogleGroup](https://github.com/senny/emacs-eclim/issues). Would be nice to give feedback and fix open bugs.

Other than that, there's still plenty of potential that `eclim` offers that could be integrated. If you feel like something is missing just dive in.

Please contact @jchochli to synchronize your efforts. Thank you so much :yellow_heart:

**Comment by lins05** [comment]
@senny Thanks, would take a look soon. BTW the two links you give should be swapped :)

@jchochli I'm still getting myself familiar with the whole project, but I'm ready to discuss about the project at any moment.

**Comment by jchochli** [comment]
@lins05 I'm still away on vacation this week.  Also still getting familiar with the code. 

Spent a few hours trying to edit a JavaScript file with emacs-eclim enabled last week, but eclipse luna kept crashing with heap error despite trying different settings.  Will probably switch to tern for JavaScript I guess.

Was looking at issue #133, what's the oldest version of emacs we are trying to support?

**Comment by fred-o** [comment]
Very happy to hear that people are interested in the project :)

I'd say that it's now up to you what version(s) of emacs you feel comfortable supporting. Some people still run emacs 23 for various reasons, and I tried to keep things backwards compatible. I was problably not 100% successful though :)

**Comment by Peaker** [comment]
How hard would it be to add C\C++ support?

A friend of mine added eclim/C support to Sublime in an evening or two. Would emacs support be comparable?

**Comment by jchochli** [comment]
You're welcome to try it.  A couple of evenings sounds like a very short time to me, but my Elisp skill isn't that great yet.

Alternatively, I've read good things about CEDIT for C/C++ and possibly projectile: https://github.com/JulianEberius/Subclim

**Comment by Peaker** [comment]
Ok, I added preliminary/basic C support in an evening&a-half :)

It's not polished yet, and has rough edges, and is done with some cut&paste hackery...

I intend to clean it up and push a fork (hopefully soon).

**Comment by dbushenko** [comment]
jchochli: How is it going with the eclim project? Do you plan to start merging the pull requests soon?

**Comment by jchochli** [comment]
@dbushenko: Okay I'll spend some time on it this weekend, sorry I've been so slow.  Are there any current pull requests in particular that you'd like to see merged?

Longer term, it would be nice to add support for the features in the latest eclim.  Java debugging would be nice and allow me to stay in emacs instead of constantly going back to eclipse.

**Comment by dbushenko** [comment]
@jchochli: Nothing in particular, I just think that it is important to verify and merge pull requests to keep the project moving. If noone merges the pull requests then why would anyone do them?

**Comment by jchochli** [comment]
@dbushenko Yes, I agree.  Thanks for the gentle nudge.

**Comment by besief** [comment]
Just a heads up: Pull Request #133 would be must useful to have right now, as otherwise this thing just does not work under up-to-date emacs, eclim, eclipse. :)

**Comment by jchochli** [comment]
Hi @besief, I just asked @dcolascione to rebase #133.

What's broken for you without #133?  I'm using up-to-date emacs (24.5), eclim, and eclipse (luna).  Thanks

**Comment by besief** [comment]
Well, mostly `member-if` is not found, which made it so that I could not even open any file with emacs-eclim active, because some post-command-hook was calling that. After changing it locally to `cl-member-if`, everything *mostly* works. I still have some issues, but I'm not sure whether they're my own fault, as I'm rather new to this whole emacs thing.
