### ISSUE TITLE
invalid completion for "java." etc.

### ISSUE THREAD

**Issue by lotabout** [senny/emacs-eclim#162]
For example, 
```
import java.u<company complete>
```
Then option `java.util` show up, and there are two issues here:
1. I cannot input any character to continue the completion, the error message says: `Matching input is required`
2. If I select one completion, for example `java.util`, then the result would be:
```
import java.java.util
```
After a litter survey, I found that it is related to the selection of prefix. That means company would select 'u' as prefix, and replace it with `java.util` and results in `java.java.util`.

In eclim(vim), the completion process would manually delete the prefix from the result (see "autoload/eclim/java/complete.vim:92"). So how do you guys deal with this situation? Thanks!

Emacs: 24.4.1
emacs-eclim: emacs-eclim-20140809.207

**Comment by jchochli** [comment]
Hi,  thanks for creating the issue.

Not sure if I understand 1.  When I type: 'import java.uti' it does show completions.  Also with 'C-.' bound to company-complete, if I type: import java.u then 'C-.' I also see completions.  

2. I do get this same behavior.

I'll see if I can take a shot at improving it this weekend or pull requests welcome (testing the existing pull requests now).  I usually just use organize imports to create imports for me.

**Comment by lotabout** [comment]
Thanks for responding.
The first issue is like: When I type "import java.u", there will be completions, for example, "java.util". Then I want to narrow down the completion list by input another letter 't'. Now the letter 't' fail to appear on the screen. And the error message shows up.

Thanks!

**Comment by kleewho** [comment]
@lotabout You reported two issues here and one of them should already be fixed. The other one wasn't reproduce by anyone. Could you upgrade `emacs-eclim` and possibly other packages as well and check whether the issues are gone or not.

**Comment by kleewho** [comment]
I'm closing the issue cause the reproduced part was fixed. If @lotabout or anyone else still have the issue then we can reopen this issue or create new one.

**Comment by lotabout** [comment]
@kleewho Sorry for late reply. I tested the new version(emacs-eclim-20150731.728). And it is fixed.

Thanks for your work!
