### ISSUE TITLE
Wrong number of arguments when using 'eclim-java-import'

### ISSUE THREAD

**Issue by sollidsnake** [senny/emacs-eclim#179]
When I try to use 'eclim-java-import', it gives me the error "Wrong number of arguments", see the image:
![snapshot9](https://cloud.githubusercontent.com/assets/1778350/7888827/ab4e30be-0611-11e5-9400-d485ab760d62.png)

Importing the same class under vim + eclim works.

**Comment by jchochli** [comment]
Confirmed, looks like it's expecting a type to be passed in.  I'll look through history to see if it's a recent change or has been like that for a while.  It's not one of the commands that has a key binding by default.

For now, maybe try eclim-java-import-organize or eclim-problems-correct.

**Comment by sollidsnake** [comment]
No problem. It's just that I've migrating from vim and I've always used :JavaImport. I'll try those you mentioned. Thanks

**Comment by jchochli** [comment]
Great and welcome!  Let us know if any features you commonly used are missing.  I'd like to eventually implement the features from the latest eclim.

**Comment by sollidsnake** [comment]
Thanks, the emacs community is awesome :)
I just tried import organize. It works great. As for missing features, there are two issues that I'm dealing with:
- Sometimes, when calling completion, emacs freezes. I can't debug. It just stops responding and it consumes 100% of cpu. Maybe it's the eclim version, I don't know. I'll try updating it later. If it still happens, and I get some debug information, I'll file a bug.
- emacs-eclim has to save the file every time completion is triggered. That makes things slow if you have instant completion. In vim, the completion is instantaneous, there's no delay. But I changed my completion configuration for Java and I'm getting used to it. It's not so good as vim, though.

Besides that, everything seems perfect; better than vim in most cases. Thanks for this nice extension :)

**Comment by jaigupta** [comment]
It seems like eclim-java-import was not meant to be interactive function as it has a 'type' parameter which is not optional.

Also, it needs the complete path to the type being imported (with the package path).
We should remove this implementation from being interactive and supply another implementation which uses symbol-at-point.

**Comment by jchochli** [comment]
@jaigupta Yep, I agree
