### ISSUE TITLE
Missing argument for eclim-java-find-declaration

### ISSUE THREAD

**Issue by basus** [senny/emacs-eclim#180]
Trying to use `eclim-java-find-declaration` I see an error message in the minibuffer: `Missing argument for option: n`.

**Comment by jchochli** [comment]
I haven't been able to reproduce that error.  Are you using the latest emacs-eclim, eclim, Java 1.7+ and Eclipse Luna (4.4.x)?

**Comment by basus** [comment]
Actually seems to be working now. I'll reopen if this re-occurs.

**Comment by emmanueltouzery** [comment]
I am getting this error right now.

Eclipse:

    Version: Mars.1 (4.5.1)
    Build id: Z20151013-1620

Java:

    openjdk version "1.8.0_65"
    OpenJDK Runtime Environment (build 1.8.0_65-b17)
    OpenJDK 64-Bit Server VM (build 25.65-b01, mixed mode)

the `eclimd` server prints this at the time of the error:

    NGSession 1: 127.0.0.1: org.eclim.command.Main exited with status 1

That said it's my first attempt at setting up `eclim`, it's very likely I misconfigured something. Using it through the `spacemacs` integration.

**Comment by nloyola** [comment]
Can you turn on debug messages and paste what gets added to the `*Messages*` buffer?

To turn on debug messages use `M-: (setq eclim-print-debug-messages t)`. Then call `M-x eclim-java-find-declaration`. After this you should see a line like the following added to the `*Messages*` buffer.

```
Executing: /home/user/bin/eclim -command java_search -n my_project -f src/main/java/org/company/project/MyClass.java -o 1151 -l 3 -x declaration
```

**Comment by yuandaxing** [comment]
I have the same problem: 
helm-M-x: Missing argument for option: p
don't know how to solve
