### ISSUE TITLE
Java hierachy link markup is missing or wrong

### ISSUE THREAD

**Issue by mnp** [senny/emacs-eclim#181]
Running eclim-java-hierarchy on a class name gives me a valid tree, however, only the first line is drawn with the blue-underline link markup face; I expected every line to be drawn with link markup pointing to the definition of each class.  Also, this first line's link points at com.the.whole.class.name instead of ClassName.java as expected.

    => public class RootEntityCollection                 <-- link text, but wrong target
      => public class SimplifiedConcurrentHashMap        <-- plain text, no link
        => public class ConcurrentHashMap                <-- plain text, no link

Versions

     (emacs-version)
     "GNU Emacs 24.4.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21)
      of 2014-10-20 on builder10-9.porkrind.org"

    (pkg-info-package-version 'emacs-eclim)
    (20150522 1138)

**Comment by kleewho** [comment]
It won't be very helpful but it does work for me. I'll update emacs-eclim and check once again

**Comment by kleewho** [comment]
Unfortunately it works for me. Currently I have installed:

```elisp
(pkg-info-package-version 'emacs-eclim)
(20150528 1637)
```

Update and try again and in the meantime someone with more knowledge might come ;)

**Comment by mnp** [comment]
Thanks.  If not, I'll try to throw up a patch.

**Comment by kleewho** [comment]
Great! I just wouldn't know from where should I start.

**Comment by kleewho** [comment]
@mnp I checked it once again... I think I was calling `eclim-java-call-hierarchy` which I think is working fine. I confirm that `eclim-java-hierarchy` does not work

**Comment by kleewho** [comment]
Close by 08c73cc
