### ISSUE TITLE
Java find references don't find references

### ISSUE THREAD

**Issue by kleewho** [senny/emacs-eclim#184]
When calling `eclim-java-find-references` I get buffer with this content:

```
-*- mode: eclim-find; default-directory: /home/corpo-user/Dokumenty/Projekty/Acme/foo/foo-domain/src/main/java/com/acme/domain -*-

eclim java_search -p ChannelView
```

and as you can see zero results. Making the same call from command-line:

```
./eclim -command java_search -p ChannelView 
[{"filename":"/home/corpo-user/Dokumenty/Projekty/Acme/foo/foo-domain/src/main/java/com/acme/domain/ChannelView.java","offset":304,"length":11,"line":12,"column":14,"message":"com.acme.domain.ChannelView"}]
```

Obviously the call is wrong cause even looking at the function definition I see that the call itself should at least have `-x references` somewhere. Calling it from cli like this:

```
./eclim -command java_search -p ChannelView -t all -x references
```

returns plenty of results

**Comment by kleewho** [comment]
It seems that content of eclim find buffer don't have anything to do with what was actually sent

**Comment by jchochli** [comment]
It's working for me when I have point on any text.

**Comment by kleewho** [comment]
Lucky guy! If the situation occur I will try to reproduce it in my test project. I have prepared test project but I'm looking for situation when it's failing. If possible do not close this issue yet as I'm sure that it's failing in some situations

**Comment by kleewho** [comment]
I found the problem... consider this project:

```
parent
 |- lib
 |- proj
```

`lib` is a dependency of `proj` and both of them are submodules of `parent`. Looking for anything in `lib` is failing probably because eclim returns wrong project for files present in `lib`. Command:

```
~/opt/eclipse/eclim -command project_by_resource -f /home/user/parent/lib/src/main/java/com/acme/Library.java
```
instead returning `lib` returns `parent` and then eclim can't find any references. Calling `java_search` with fixed project name returns correct list of references but call with wrongly set project name returns empty list.

**Comment by kleewho** [comment]
Reimport did the trick. Closing cause it doesn't sound like an `emacs-eclim` issue

**Comment by jchochli** [comment]
You're a fireball of activity!  :fire:

**Comment by liujoey** [comment]
I've experienced the same issue, it starts since my last updates of packages.
Now eclim-java-find-declaration giving me nothing. Reimport does not work for me.
Here is the content of eclim-find buffer:

```
-*- mode: eclim-find; default-directory: /home/joey/workspace/icon/libicon/src/main/java/com/philips/prna/util/ -*-

eclim java_search -p TermMap
```

I have icon as the parent project, and libicon is one of the sub-project.

**Comment by kleewho** [comment]
I've been experiencing some similar problems from time to time but I can't seem to find any pattern. @liujoey can you describe how exactly your project looks like? How do you import it? I've got concerns about multimodule maven project with parent being simple `pom` that groups couple projects. Do you have similar setup? I'm willing to try to tackle this once again, but I'm looking for some inspiration

**Comment by liujoey** [comment]
It was working last week. Then I did Emacs package update earlier this week, don't remember what's the version I was using previously.

I don't think it's anything wrong with Eclim. I've no problem to jump to declaration when using Vim eclim plugin. And from the command line, the eclim command result looks also good.

```
$ /opt/eclipse_luna/eclim -command java_search -p TermMap
[{"filename":"/home/joey/workspace/icon/libicon/src/main/java/com/philips/prna/util/TermMap.java","offset":328,"length":7,"line":17,"column":14,"message":"com.philips.prna.util.TermMap"}]
```

It's just that the updated emacs-eclim can't jump to the file, I guess.

**Comment by liujoey** [comment]
I tested `eclim-java-find-type`, and it works
Now I was confused. The code of `eclim-java-find-declaration` uses `-n -f -o` options for `java_search`.
```lisp
(defun eclim-java-find-declaration ()
  "Find and display the declaration of the java identifier at point."
  (interactive)
  (let ((i (eclim--java-identifier-at-point t)))
    (eclim/with-results hits ("java_search" "-n" "-f" ("-o" (car i)) ("-l" (length (cdr i))) ("-x" "declaration"))
      (eclim--find-display-results (cdr i) hits t))))
```
When I run command:
```
/opt/eclipse_luna/eclim -command java_search -n -f -o TermMap -l 7 -x declaration
```
I got `Missing argument for option: n`

according to the [eclim document](http://eclim.org/vim/java/search.html), there's no `-n` or `-f` options, it only supports `-p`, am I missing something here?

**Comment by kleewho** [comment]
I think eclim documentation might be outdated. Look here. https://github.com/ervandew/eclim/blob/master/org.eclim.jdt/java/org/eclim/plugin/jdt/command/search/SearchCommand.java#L79-L92
