### ISSUE TITLE
complete doesn't work well whit ac-emacs-eclim-source

### ISSUE THREAD

**Issue by LuoPX-15510486969** [senny/emacs-eclim#209]
when i use ac-emacs-eclim-source to do auto-complete,but every time it shows the other information which I don't need. Look at the following screenshot.

![qq 20150713152454](https://cloud.githubusercontent.com/assets/13256245/8648063/010348a4-2990-11e5-99f5-7def447728f0.png)

![qq 20150713152209](https://cloud.githubusercontent.com/assets/13256245/8648073/1bf40fcc-2990-11e5-8099-c6ea0f89c698.png)

**Comment by kleewho** [comment]
Thanks. Can you give info about `emacs-eclim` version? Use `pkg-info-package-version` with `emacs-eclim`

**Comment by LuoPX-15510486969** [comment]
I didn't install it from list-package.I download it from github 5 hours ago and i am sure it is the lastest version.

**Comment by LuoPX-15510486969** [comment]
these information is detrieved from emacs-eclim-pkg.el

(define-package "emacs-eclim" "0.3"
  "An interface to the Eclipse IDE."
  '((dash "2.11.0")
    (json "1.2")
    (popup "0.5.2")
    (s "1.9.0")))

**Comment by dsjlzh** [comment]
ac-emacs-eclim-source.el
```patch
 (ac-define-source emacs-eclim
                   '((candidates . eclim--completion-candidates)
-                    (action . eclim--completion-action)
+                    (action . ac-emacs-eclim-action)
                     (prefix . eclim-completion-start)
                     (document . eclim--completion-documentation)
                     (cache)
```

**Comment by kleewho** [comment]
@dsjlzh What exactly is passed to `action`? Maybe indeed it fixes the behaviour, but I'd like to understand it a little bit better first

**Comment by LuoPX-15510486969** [comment]
(ac-define-source emacs-eclim
                   '((candidates . eclim--completion-candidates)
-                    (action . eclim--completion-action)
+                    (action . ac-emacs-eclim-action)
                     (prefix . eclim-completion-start)
                     (document . eclim--completion-documentation)
                     (cache)



after do that, it doesn't work too.

**Comment by skybert** [comment]
This regression was introduced in 0215ce0155ca0105d08a73da7d0e9bd9405b48a6.

**Comment by skybert** [comment]
@kleewho If I read the source correctly, `eclim--completion-action` was changed in 0215ce0155ca0105d08a73da7d0e9bd9405b48a6 to require two arguments. Without these two arguments, the call fails, as reported in this issue.

 `ac-emacs-eclim-action` correctly passes these two values to `eclim--completion-action`.

I can confirm that the fix propsed by @dsjlzh works. Thanks, @dsjlzh!

**Comment by kleewho** [comment]
Oh my... It was me :panda_face: Thank you all!
