### ISSUE TITLE
Show something like eclipse outline

### ISSUE THREAD

**Issue by kleewho** [senny/emacs-eclim#216]
Outline in eclipse is an overview of all classes (with methods and fields) for current file. It was requested by @gopar in this https://github.com/senny/emacs-eclim/pull/211. 

In general it's much better to expose it on `eclim` side and just consume the data in `emacs`.

**Comment by liujoey** [comment]
in spacemace, you could use `SPC` `s` `l` to trigger `spacemacs/jump-in-buffer` to get a list of all functions in current buffer. It's looks and uses almost the same as the eclipse outline.

**Comment by kleewho** [comment]
@liujoey This is awesome! One important thing it's working only if one have enabled semantic layer... I was wondering whether to keep it or not, but now it's definitely going to stay with me. 

For all non spacemacs users. Semantic layer means just semantic tags that are created by bovinator or some other cedet related parser

**Comment by kleewho** [comment]
Worth mentioning is that @gopar reopened the discussion about outline by creating outline version for java on eclim project https://github.com/ervandew/eclim/issues/250. Good job

**Comment by gopar** [comment]
@liujoey Well that is sure handy. Well that takes care of what I wanted. 

Not sure if I'll continue to try to add the outline command to eclim proj.

**Comment by jchochli** [comment]
I make due with 'M-x imenu' combined with ido-vertical-mode.

**Comment by kleewho** [comment]
I just checked and both methods seems to be working well with 1.8 interfaces even with default implementation. I think we should at least write on wiki how to setup outline

**Comment by skybert** [comment]
FYI: if you want to have a dedicated buffer listing the imenu for the buffer you're working on, you can use imenu-list: https://github.com/bmag/imenu-list.

**Comment by gopar** [comment]
Just a quick question for all you savy emacs users. Does anyone know how to make semantic just show classes, functions and variables? When I call it, it shows me the libraries that I imported and the package namespace.

**Comment by kleewho** [comment]
Any volunteer to add info about setting outline up to wiki? I'll close the issue right after including any information in wiki

**Comment by kleewho** [comment]
@gopar, how exactly do you use it?

**Comment by gopar** [comment]
@kleewho I call `helm-semantic`. I get the package namespace and library imports mixed in with the results

**Comment by kleewho** [comment]
@gopar I get the same. Looked for some time into sources to figure out is there any way to configure this but found nothing

**Comment by gopar** [comment]
@kleewho Yeah, I thought I just sucked at reading documentation but it looks like you can't modify it. Oh well

**Comment by gopar** [comment]
Created wiki: https://github.com/senny/emacs-eclim/wiki/Eclipse-Outline
Please change as needed.
Close this issue?

**Comment by kleewho** [comment]
@gopar, thank you very much!
