### ISSUE TITLE
Java Classpath Commands *Feature*

### ISSUE THREAD

**Issue by gopar** [senny/emacs-eclim#225]
Be able to edit the classpath file, eclim in VIM already has the ability of doing this. I _plan_ on doing this with my free time or if anyone is faster than me then go right ahead :D 

One question I do have is that [eclim has this in a different section](http://eclim.org/cheatsheet.html#java-classpath-commands), so should the project have file just for these type of commands (eclim-java-classpath.el or eclim-classpath.el)? Any info on how to get started would be appreciated

**Comment by gopar** [comment]
Have a draft of a draft here: https://github.com/senny/emacs-eclim/compare/master...gopar:issue225

**Comment by kleewho** [comment]
That was fast... Mr, you seem to have quite a lot of free time

**Comment by kleewho** [comment]
I'll take a look of course

**Comment by gopar** [comment]
Haha some days yes and others not so much. Also its just one command right now. Just wanted to know how you guys would like it structured.

**Comment by kleewho** [comment]
I'm not an elisp expert but I can give it a try

I think `classpath-quit` could be just `kill-buffer` so you don't have to have function there.
If you already use `switch-to-buffer` I think you don't have to use `with-current-buffer` cause there's no point of it. The `answer` might be named better, cause right now it's rather not descriptive (especially that there's no question anywhere). In general maybe it's good idea to create major-mode. Take a look how major-mode is created in [eclim-problems.el](https://github.com/senny/emacs-eclim/blob/master/eclim-problems.el#L78). 

Usually that's how review in my team looks like. More or less. :panda_face:

**Comment by gopar** [comment]
Scanning over the eclim files. Found [these four functions ](https://github.com/senny/emacs-eclim/blob/master/eclim-java.el#L177-L190) already defined. Should I import them and use them to just grab the input they provide? Or move them to my file? They don't seem to be used anywhere except for one instance in the [`eclim-debug`] (https://github.com/senny/emacs-eclim/blob/master/eclim-debug.el#L52)
Also my "a lot of free time" ends tomorrow for a couple of days :P

**Comment by kleewho** [comment]
If they're about classpath then it's better to move them to the file that suggest that classpath related stuff is there

**Comment by gopar** [comment]
Hmmm this is weird. I can't find the command for calling `NewVarEntry`. It looks like it's implemented using vimscript (I think that's what it's called). Is there a way to call functions like that from emacs?

**Comment by gopar** [comment]
Wanted to give a heads up that I added some more code. Also, since I took the recommendation about creating a major-mode for the buffer, I have no way of finding out what current project the user is in. The reason why I want to know this is to add/delete variables and src directories right from the buffer. But in order to do that I need to know the current project. 
I was thinking of creating a variable to hold the project whenever the buffer was created and just pass that around as needed. What do you guys think of that? Or did I overlook some function that would return the current project? I already tried `eclim-project-name` and some others

**Comment by kleewho** [comment]
Can you show some code? I think I'm better when I can take a look at something

**Comment by kleewho** [comment]
From what I know eclim-project-name should be what you're looking for... but maybe I misunderstood what you wrote.

**Comment by gopar** [comment]
Oops, forgot to add link. https://github.com/senny/emacs-eclim/compare/master...gopar:issue225

**Comment by kleewho** [comment]
@gopar you're saying that `eclim-project-name` is set to `nil`? We have some problems with it https://github.com/senny/emacs-eclim/issues/232

**Comment by kleewho** [comment]
Check this [PR](https://github.com/senny/emacs-eclim/pull/235). It should fix all issues with `eclim-project-name`. I hope it'll resolve your problem as well.
