### ISSUE TITLE
Adding a new project in Eclipse breaks many things

### ISSUE THREAD

**Issue by ulises** [senny/emacs-eclim#233]
I know that "breaks many things" is a bad description, but that's what's happening, e.g. I can't switch buffers any more.

The problem happens if I add a new project to Eclipse in Eclipse itself. The message I keep getting is:
````
    Error in post-command-hook (global-eclim-check-buffers): (error "invalid project: NEW PROJECT HERE")
````

**Comment by gopar** [comment]
Can you provide version of eclim, eclipse and emacs?

I tried creating a new project with my current setup and everything seems to work alright.

**Comment by kleewho** [comment]
I can do it for him: 

> Forgot to add:
    eclim 2.5.0
    Eclipse Mars 4.5.0
    Emacs 24.5 (running on OS X, installed via brew)

I guess we can assume newest emacs-eclim.

**Comment by ulises** [comment]
Apologies. Yes, I'm running the latest version coming from MELPA (I'm guessing it's master).

**Comment by ulises** [comment]
This is old enough, and can't reproduce.
