### ISSUE TITLE
Compile error when byte-compiling

### ISSUE THREAD

**Issue by ackalker** [senny/emacs-eclim#236]
Updating `emacs-eclim-20150815.237` from MELPA, I'm getting the following error during byte-compiling:
```
Compiling file /home/miki/.emacs.d/elpa/emacs-eclim-20150815.237/ac-emacs-eclim-source.el at Sat Aug 15 15:13:01 2015
Entering directory `/home/miki/.emacs.d/elpa/emacs-eclim-20150815.237/'
ac-emacs-eclim-source.el:33:1:Error: Cannot open load file: no such file or directory, auto-complete
```
Note that I'm using `company` for autocompletion, I do not have the `auto-complete` package installed.

**Comment by kleewho** [comment]
Thanks. Just to make it clear. You are able to use `eclim`, right?

**Comment by ackalker** [comment]
Sure, the error isn't fatal, `eclim` works fine. Thanks for creating this package :)

**Comment by kleewho** [comment]
I'm closing this cause this error will be fixed in this issue all together with other compile problems https://github.com/senny/emacs-eclim/issues/208
