### ISSUE TITLE
toggle-maximize-buffer doesn't exist?

### ISSUE THREAD

**Issue by ulises** [senny/emacs-eclim#266]
I'm getting a `Symbol's function definition is void: toggle-maximize-buffer` which comes from here: https://github.com/senny/emacs-eclim/blob/master/eclim-debug.el#L96

How to reproduce:

1. run gradle/ant test in debug mode
2. C-c C-e p a (attach to running test)
3. Accept default port (5005)

Emacs version: 24.5
Eclim version: .emacs.d/elpa/emacs-eclim-20150816.220 (via spacemacs)

**Comment by gopar** [comment]
This is similar to #253

**Comment by ulises** [comment]
Thanks!
