### ISSUE TITLE
Problem with tramp when using .authinfo.gpg

### ISSUE THREAD

**Issue by YorkZ** [senny/emacs-eclim#268]
In the file ~/.authinfo.gpg, I have the following entry:

machine MY-SYSTEM-NAME port sudo login root password MY-ROOT-PASSWORD

Whenever i press C-x C-f /sudo::/etc/hosts RET, my Emacs locked up after producing the message:

    Decrypting /home/LOGIN-NAME/.authinfo.gpg...done.

I then had to press C-g to get out.

Thanks,
York

**Comment by nloyola** [comment]
How is this issue related to `emacs-eclim`? Did you post this issue to the correct repository?

**Comment by YorkZ** [comment]
> How is this issue related to emacs-eclim? Did you post this issue to the
> correct repository?


It actually took me some time to track down to emacs-eclim. I'm pretty sure
emacs-eclim has caused this problem. Here's what I did:

1. I noticed that I had this issue.
2. I figured out that if I didn't have `(require 'elime)` in my .emacs, the
   issue went away.
3. I removed everything in my .emacs file, and tested again, verified that
   I didn't have this problem.
4. I then added the following three lines:

   `(require 'cl-lib)`
   `(add-to-list 'load-path PATH/TO/EMACS-ECLIM)`
   `(require 'eclim)`

   to my .emacs, the problem came back again!

Wasn't you able to reproduce this issue? By the way, I tested it with commit 846fb89.

**Comment by nloyola** [comment]
The Emacs-Eclim repository was moved to https://github.com/emacs-eclim/emacs-eclim. Would you mind submitting your issue to this new repository?

By the way, I was able to reproduce your issue with the latest commit in the new repository.

Thanks

**Comment by nloyola** [comment]
FYI: to add more details for this problem, I just came across these posts: 

* http://emacs.stackexchange.com/questions/4234/cannot-edit-a-file-as-root-if-authinfo-gpg-file-exists.

* https://github.com/bbatsov/projectile/issues/835

* https://github.com/bbatsov/prelude/issues/594

**Comment by YorkZ** [comment]
Thanks for letting me know the new repository, I didn't know :)

I've already submitted [this issue] (https://github.com/emacs-eclim/emacs-eclim/issues/15 ) to the new repository.
