### ISSUE TITLE
url-insert-file-contents: http://melpa.org/packages/emacs-eclim-20160318.1747.tar: Not found

### ISSUE THREAD

**Issue by xianghx** [senny/emacs-eclim#275]
url-insert-file-contents: http://melpa.org/packages/emacs-eclim-20160318.1747.tar: Not found

**Comment by nloyola** [comment]
This link is no longer valid since it is not the version of **eclim** at the Melpa web site. Please try downloading the latest. 

At the time I'm writing this response the link to the latest version is: 

https://melpa.org/packages/emacs-eclim-20160328.1532.tar
