### ISSUE TITLE
emacs-eclim renamed to eclim in melpa

### ISSUE THREAD

**Issue by harishkrupo** [senny/emacs-eclim#283]
Emacs-eclim is not available in melpa. It is renamed as eclim. Please change the readme.md's installation section. Also company-emacs-eclim.el isn't available in eclim and needs to be installed manually

**Comment by nloyola** [comment]
Development on this project has moved to https://github.com/emacs-eclim/emacs-eclim. What you asked for above has already been done in this other repository.

Ideally, it would be great to add a message to this project's README file to state that development has moved. But, unfortunately none of this projects maintainers are available to do so.

**Comment by jchochli** [comment]
@nloyola  I have write access to the repository, tried making the notice in the README a little more noticeable.  Should I sprinkle more notices throughout the README?  Let me know.

**Comment by harishkrupo** [comment]
Also the eclim package in melpa doesn't have company-emacs-eclim.el. I had to install it explicitly. It is not mentioned in the readme in emacs-eclim/emacs-eclim.

**Comment by nloyola** [comment]
@jchochli Thanks so much for updating the README. Would you also be able to put a similar message on the Wiki: https://github.com/senny/emacs-eclim/wiki. Just in case. Or maybe, have a link to the new Wiki?

https://github.com/emacs-eclim/emacs-eclim/wiki

Thanks

**Comment by nloyola** [comment]
@harishkrupo there is a section titled [Configuring company-mode](https://github.com/emacs-eclim/emacs-eclim/blob/master/README.md#configuring-company-mode) in the README file. 

What do you think is missing in this section?

**Comment by harishkrupo** [comment]
The new version (from melpa) doesn't contain company-emacs-eclim.el.
This causes 
`(require 'company-emacs-eclim)` to fail.
So one has to explicitly install the package company-emacs-eclim. 
Please add the installation instruction to the README.

**Comment by nloyola** [comment]
@harishkrupo I have created issue emacs-eclim/emacs-eclim#13. I will update the README file shortly.
