### ISSUE TITLE
No "Create type" function?

### ISSUE THREAD

**Issue by gabrielps** [senny/emacs-eclim#286]
Hi there. First of all, thank you for porting eclim to emacs ;)

I've been searching for the new type function (vim's :JavaNew) and didn't found it. Are you planning to include it? Is there a way to use it?

Cheers.

**Comment by nloyola** [comment]
Development on this project has moved to [emacs-eclim/emacs-eclim](https://github.com/emacs-eclim/emacs-eclim). Are you using the version published by that repository?

**Comment by gabrielps** [comment]
I'm not sure, im using the one spacemacs provides. I will check there and see if I can find something.
