### ISSUE TITLE
Invalid function: eclim/execute-command

### ISSUE THREAD

**Issue by aisbaa** [senny/emacs-eclim#80]
Hi, just updated eclim to 1cee790483ee80ac166c78468d2dfc8a518782e2 commit, calling **eclim--complete** from **java-mode** results in:

```
Making completion list...
eclim/project-list: Invalid function: eclim/execute-command
```

Calling **eclim-java-import-organize** from the same **java-mode** results in:

```
call-interactively: Symbol's value as variable is void: res
```

Here is eclim config http://pastebin.com/fCSGR1hm and full full config https://github.com/aisbaa/prelude

**Comment by kleewho** [comment]
Even though this issue is very old I do get similar problems from time to time with `eclim-project-name` being set to `nil`.

**Comment by kleewho** [comment]
Closing in favor #232 Issue which seems to be similar. There's not much more information in this one

**Comment by lazywei** [comment]
Is this fixed? I still got the same error...

**Comment by nloyola** [comment]
Development has moved here: https://github.com/emacs-eclim/emacs-eclim. Can you try it out with that version?
