### ISSUE TITLE
Symbol's function definition is void: find

### ISSUE THREAD

**Issue by daveloyall** [senny/emacs-eclim#95]
Hi.

I'm no emacs expert, so maybe this is just "user error", but here goes:

When I start a fresh emacs and issue `M-x eclim-manage-projects`, I get the message `Symbol's function definition is void: find`.

After looking around for a while, I realized that various calls like `(find ...)` are all over `eclim.el`, and indeed that function wasn't defined.  But I found a defun for it here:

```
hobbes@metalbaby:~/src/emacs$ find . -name *.el -exec grep -H  "^(defun find (" {} +
./emacs24-24.2+1/lisp/emacs-lisp/cl-seq.el:(defun find (cl-item cl-seq &rest cl-keys)
```

...So, long story short, I had to `(require 'cl)`, then `eclim-manage-projects` works.

So maybe emacs-eclim should call `(require 'cl)` on its own.  Is that how that works?

_Now, I have read that it's not popular to make a package depend on cl at runtime, but it's accepted to make it depend on it at compile time...  And indeed I seem to recall cl being loaded during compile when I first installed emacs-eclim.  Personally, I don't mind having cl loaded, so I consider my problem solved, but, I just thought that you might want to know about this._

Cheers,
--Dave

**Comment by daveloyall** [comment]
This is the oldest still-open issue I have posted on github.  In looking over it, I think it can be closed.  Please comment if I should reopen it, or just reopen it if you have the bit.

**Comment by dgutov** [comment]
Doesn't look fixed to me, e.g.:

https://github.com/senny/emacs-eclim/blob/846fb89539318a2f010505d6f6301593a9ea666b/eclim-project.el#L340
https://github.com/senny/emacs-eclim/blob/846fb89539318a2f010505d6f6301593a9ea666b/company-emacs-eclim.el#L47

While there's only a `(require 'cl)` in a test file.

**Comment by daveloyall** [comment]
ok, dgutov.  Sorry I missed it; I haven't used eclim recently.

**Comment by jchochli** [comment]
Development has moved to https://github.com/emacs-eclim/emacs-eclim

**Comment by dgutov** [comment]
@jchochli Ah cool. Looks like this problem is indeed fixed over there already.

**Comment by daveloyall** [comment]
That's good news!
